#!/bin/bash

CURRENT_DIR=$(pwd)
DIR=$(dirname $0)
if [ $DIR == '.' ]; then
	DIR="$CURRENT_DIR"
fi

init(){
	if [[ "$OSTYPE" == "darwin"* ]]; then
		cat /dev/null > "${DIR}/log"
		return;
	elif [["$OSTYPE" == "linux-gnu"]]; then
		echo "Linux";
	elif[["$OSTYPE" == "cygwin"]]l then
		echo "cygwin : linux emulator for win"
	elif [[ "$OSTYPE" == "msys" ]]; then
		echo  "mysys : light-weight shell for windows"
	elif [[ "$OSTYPE" == "win32" ]]; then
	        echo "Don't think we need it"
	elif [[ "$OSTYPE" == "freebsd"* ]]; then
	        echo "BSD"
	else
	        echo "No Support"

	fi
}


function usage()
{
    echo "Change your wallpaper dynamically to the Photo of the day of Nat Geo."
    echo ""
    echo "Arguments"
    echo " -s : Initialize automation of wallpaper"
    echo " -d : Stop|Delete automation of wallpaper"
    echo ""; 1>&2; exit 1;
}

init

while getopts ":hsd" o; do
    case "${o}" in
        s)
            (crontab -l ; echo "* * * * * $DIR/switcher.sh >> $DIR/log 2>&1") | crontab -
            exit 1;
            ;;
        d)
            crontab -l | grep -v "$DIR/switcher.sh >> $DIR/log 2>&1"  | crontab  -
            exit 1;
            ;;
        h | *)
            usage
            exit 1;
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${s}" ] || [ -z "${p}" ]; then
    usage
fi
